title: Shahiryar Saleem # your name (or website title) here
logo: "/images/profile-photo-bg-blu-halo.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  2+ years of experience in developing creative and critical solutions that used large datasets. Has 5+ years of international and remote collaborative experience. Posses Bachelor's in Computer Science from Asia Pacific University, Malayisa. 
  <br><br>
  Currently, garnaring diverse experience in Data Science and Machine Learning through independent projects.
  <br><br>
  <script src="https://platform.linkedin.com/badges/js/profile.js" async defer type="text/javascript"></script>
  <div class="badge-base LI-profile-badge" data-locale="en_US" data-size="medium" data-theme="light" data-type="VERTICAL" data-vanity="shahiryar-saleem-459b5a146" data-version="v1"><a class="badge-base__link LI-simple-link" href="https://pk.linkedin.com/in/shahiryar-saleem-459b5a146?trk=profile-badge">Shahiryar Saleem</a></div>
              
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-LF8TRG8CXJ # your Google Analytics tracking ID here
