title: Shahiryar Saleem # your name (or website title) here
logo: "/images/profile-photo-bg-blu-halo.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  2+ years of experience in developing creative and critical solutions that used large datasets. Has 5+ years of international and remote collaborative experience. Posses Bachelor's in Computer Science from Asia Pacific University, Malayisa. 
  <br><br>
  Currently, garnaring diverse experience in Data Science and Machine Learning through independent projects.
  <br><br>
  <a href="https://www.linkedin.com/in/shahiryar-saleem-459b5a146/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-LF8TRG8CXJ # your Google Analytics tracking ID here
